apiVersion: v2
name: observability
description: A Helm chart for Kubernetes Observability Stack
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kube-prometheus-stack
    version: 81.6.7
    repository: https://prometheus-community.github.io/helm-charts