apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-service
  name: {{ .Release.Name }}-service
  namespace: highway
spec:
  ports:
    - name: 80-8080
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Release.Name }}-app
  type: {{ .Values.service.type }}
